CREATE TABLE IF NOT EXISTS "cliente_direta" (
	"eg" varchar PRIMARY KEY NOT NULL,
	"eg_dashed" varchar,
	"cnpj" varchar,
	"rede_uf" varchar,
	"site_rede" varchar,
	"nome_fantasia" varchar,
	"cod_operacao" varchar,
	"site" varchar,
	"uf" varchar,
	"cidade" varchar,
	"cod_rede" varchar,
	"rede" varchar,
	"gn" varchar,
	"sn" varchar,
	"le" varchar,
	"coordenador_trade" varchar,
	"inplant" varchar,
	"gc" varchar,
	"gc_oeste" varchar,
	"gn_sistema" varchar,
	"sn_sistema" varchar,
	"le_sistema" varchar,
	"cluster_loja" varchar,
	"cluster_rede" varchar,
	"segmentacao" varchar,
	"sub_segmentacao" varchar,
	"categoria" varchar,
	"migracao_asr" varchar,
	"programa_de_mercado" varchar,
	"status_loja" varchar,
	"loja_cd_normal_mista" varchar,
	"eg_central" varchar,
	"eg_central_2" varchar,
	"mercado_nielsen" varchar,
	"leitura_scanntech" varchar,
	"leitura_neogrid" varchar,
	"dummhumby" varchar,
	"shopping_brasil" varchar,
	"tamanho_loja" varchar,
	"cluster_trade" varchar,
	"kam_nac" varchar,
	"diretor" varchar,
	"cnpj_dup" varchar,
	"latitude" double precision,
	"longitude" double precision
);
